// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: check-oneof.proto
// Protobuf C++ Version: 5.27.0-dev

#include "check-oneof.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr Bar::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : discription_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        payload_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Bar::Bar(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct BarDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BarDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~BarDefaultTypeInternal() {}
  union {
    Bar _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BarDefaultTypeInternal _Bar_default_instance_;

inline constexpr Foo::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : properties_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        item_{},
        _cached_size_{0},
        _oneof_case_{} {}

template <typename>
PROTOBUF_CONSTEXPR Foo::Foo(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct FooDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FooDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~FooDefaultTypeInternal() {}
  union {
    Foo _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FooDefaultTypeInternal _Foo_default_instance_;
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_check_2doneof_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_check_2doneof_2eproto = nullptr;
const ::uint32_t
    TableStruct_check_2doneof_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::Bar, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::Bar, _impl_.discription_),
        PROTOBUF_FIELD_OFFSET(::Bar, _impl_.payload_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::Foo, _internal_metadata_),
        ~0u,  // no _extensions_
        PROTOBUF_FIELD_OFFSET(::Foo, _impl_._oneof_case_[0]),
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        PROTOBUF_FIELD_OFFSET(::Foo, _impl_.properties_),
        PROTOBUF_FIELD_OFFSET(::Foo, _impl_.item_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::Bar)},
        {10, -1, -1, sizeof(::Foo)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::_Bar_default_instance_._instance,
    &::_Foo_default_instance_._instance,
};
const char descriptor_table_protodef_check_2doneof_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\021check-oneof.proto\"+\n\003Bar\022\023\n\013discriptio"
    "n\030\001 \001(\t\022\017\n\007payload\030\002 \001(\014\"n\n\003Foo\022\r\n\003age\030\001"
    " \001(\005H\000\022\021\n\007is_male\030\002 \001(\010H\000\022\017\n\005power\030\003 \001(\001"
    "H\000\022\030\n\010innerBar\030\004 \001(\0132\004.BarH\000\022\022\n\nproperti"
    "es\030\005 \001(\014B\006\n\004itemb\006proto3"
};
static ::absl::once_flag descriptor_table_check_2doneof_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_check_2doneof_2eproto = {
    false,
    false,
    184,
    descriptor_table_protodef_check_2doneof_2eproto,
    "check-oneof.proto",
    &descriptor_table_check_2doneof_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_check_2doneof_2eproto::offsets,
    file_level_enum_descriptors_check_2doneof_2eproto,
    file_level_service_descriptors_check_2doneof_2eproto,
};
// ===================================================================

class Bar::_Internal {
 public:
};

Bar::Bar(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Bar)
}
inline PROTOBUF_NDEBUG_INLINE Bar::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : discription_(arena, from.discription_),
        payload_(arena, from.payload_),
        _cached_size_{0} {}

Bar::Bar(
    ::google::protobuf::Arena* arena,
    const Bar& from)
    : ::google::protobuf::Message(arena) {
  Bar* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:Bar)
}
inline PROTOBUF_NDEBUG_INLINE Bar::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : discription_(arena),
        payload_(arena),
        _cached_size_{0} {}

inline void Bar::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
Bar::~Bar() {
  // @@protoc_insertion_point(destructor:Bar)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Bar::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.discription_.Destroy();
  _impl_.payload_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
Bar::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              PROTOBUF_FIELD_OFFSET(Bar, _impl_._cached_size_),
              false,
          },
          &Bar::MergeImpl,
          &Bar::kDescriptorMethods,
          &descriptor_table_check_2doneof_2eproto,
          nullptr,  // tracker
      };
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 23, 2> Bar::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_Bar_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Bar>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bytes payload = 2;
    {::_pbi::TcParser::FastBS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(Bar, _impl_.payload_)}},
    // string discription = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(Bar, _impl_.discription_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string discription = 1;
    {PROTOBUF_FIELD_OFFSET(Bar, _impl_.discription_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // bytes payload = 2;
    {PROTOBUF_FIELD_OFFSET(Bar, _impl_.payload_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\3\13\0\0\0\0\0\0"
    "Bar"
    "discription"
  }},
};

PROTOBUF_NOINLINE void Bar::Clear() {
// @@protoc_insertion_point(message_clear_start:Bar)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.discription_.ClearToEmpty();
  _impl_.payload_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* Bar::_InternalParse(const char* ptr,
                                        ::_pbi::ParseContext* ctx) {
  return ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
}

::uint8_t* Bar::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Bar)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string discription = 1;
  if (!this->_internal_discription().empty()) {
    const std::string& _s = this->_internal_discription();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Bar.discription");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // bytes payload = 2;
  if (!this->_internal_payload().empty()) {
    const std::string& _s = this->_internal_payload();
    target = stream->WriteBytesMaybeAliased(2, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Bar)
  return target;
}

::size_t Bar::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Bar)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // string discription = 1;
  if (!this->_internal_discription().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_discription());
  }

  // bytes payload = 2;
  if (!this->_internal_payload().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                    this->_internal_payload());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void Bar::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Bar*>(&to_msg);
  auto& from = static_cast<const Bar&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Bar)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_discription().empty()) {
    _this->_internal_set_discription(from._internal_discription());
  }
  if (!from._internal_payload().empty()) {
    _this->_internal_set_payload(from._internal_payload());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Bar::CopyFrom(const Bar& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Bar)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool Bar::IsInitialized() const {
  return true;
}

void Bar::InternalSwap(Bar* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.discription_, &other->_impl_.discription_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.payload_, &other->_impl_.payload_, arena);
}

::google::protobuf::Metadata Bar::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Foo::_Internal {
 public:
  static constexpr ::int32_t kOneofCaseOffset =
    PROTOBUF_FIELD_OFFSET(::Foo, _impl_._oneof_case_);
};

void Foo::set_allocated_innerbar(::Bar* innerbar) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_item();
  if (innerbar) {
    ::google::protobuf::Arena* submessage_arena = innerbar->GetArena();
    if (message_arena != submessage_arena) {
      innerbar = ::google::protobuf::internal::GetOwnedMessage(message_arena, innerbar, submessage_arena);
    }
    set_has_innerbar();
    _impl_.item_.innerbar_ = innerbar;
  }
  // @@protoc_insertion_point(field_set_allocated:Foo.innerBar)
}
Foo::Foo(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Foo)
}
inline PROTOBUF_NDEBUG_INLINE Foo::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : properties_(arena, from.properties_),
        item_{},
        _cached_size_{0},
        _oneof_case_{from._oneof_case_[0]} {}

Foo::Foo(
    ::google::protobuf::Arena* arena,
    const Foo& from)
    : ::google::protobuf::Message(arena) {
  Foo* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  switch (item_case()) {
    case ITEM_NOT_SET:
      break;
      case kAge:
        _impl_.item_.age_ = from._impl_.item_.age_;
        break;
      case kIsMale:
        _impl_.item_.is_male_ = from._impl_.item_.is_male_;
        break;
      case kPower:
        _impl_.item_.power_ = from._impl_.item_.power_;
        break;
      case kInnerBar:
        _impl_.item_.innerbar_ = ::google::protobuf::Message::CopyConstruct<::Bar>(arena, *from._impl_.item_.innerbar_);
        break;
  }

  // @@protoc_insertion_point(copy_constructor:Foo)
}
inline PROTOBUF_NDEBUG_INLINE Foo::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : properties_(arena),
        item_{},
        _cached_size_{0},
        _oneof_case_{} {}

inline void Foo::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
Foo::~Foo() {
  // @@protoc_insertion_point(destructor:Foo)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Foo::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.properties_.Destroy();
  if (has_item()) {
    clear_item();
  }
  _impl_.~Impl_();
}

void Foo::clear_item() {
// @@protoc_insertion_point(one_of_clear_start:Foo)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  switch (item_case()) {
    case kAge: {
      // No need to clear
      break;
    }
    case kIsMale: {
      // No need to clear
      break;
    }
    case kPower: {
      // No need to clear
      break;
    }
    case kInnerBar: {
      if (GetArena() == nullptr) {
        delete _impl_.item_.innerbar_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        if (_impl_.item_.innerbar_ != nullptr) {
          _impl_.item_.innerbar_->Clear();
        }
      }
      break;
    }
    case ITEM_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = ITEM_NOT_SET;
}


const ::google::protobuf::MessageLite::ClassData*
Foo::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              PROTOBUF_FIELD_OFFSET(Foo, _impl_._cached_size_),
              false,
          },
          &Foo::MergeImpl,
          &Foo::kDescriptorMethods,
          &descriptor_table_check_2doneof_2eproto,
          nullptr,  // tracker
      };
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 5, 1, 0, 2> Foo::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    5, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_Foo_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Foo>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bytes properties = 5;
    {::_pbi::TcParser::FastBS1,
     {42, 63, 0, PROTOBUF_FIELD_OFFSET(Foo, _impl_.properties_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 age = 1;
    {PROTOBUF_FIELD_OFFSET(Foo, _impl_.item_.age_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kInt32)},
    // bool is_male = 2;
    {PROTOBUF_FIELD_OFFSET(Foo, _impl_.item_.is_male_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kBool)},
    // double power = 3;
    {PROTOBUF_FIELD_OFFSET(Foo, _impl_.item_.power_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kDouble)},
    // .Bar innerBar = 4;
    {PROTOBUF_FIELD_OFFSET(Foo, _impl_.item_.innerbar_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // bytes properties = 5;
    {PROTOBUF_FIELD_OFFSET(Foo, _impl_.properties_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
  }}, {{
    {::_pbi::TcParser::GetTable<::Bar>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void Foo::Clear() {
// @@protoc_insertion_point(message_clear_start:Foo)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.properties_.ClearToEmpty();
  clear_item();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* Foo::_InternalParse(const char* ptr,
                                        ::_pbi::ParseContext* ctx) {
  return ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
}

::uint8_t* Foo::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Foo)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  switch (item_case()) {
    case kAge: {
      target = ::google::protobuf::internal::WireFormatLite::
          WriteInt32ToArrayWithField<1>(
              stream, this->_internal_age(), target);
      break;
    }
    case kIsMale: {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteBoolToArray(
          2, this->_internal_is_male(), target);
      break;
    }
    case kPower: {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteDoubleToArray(
          3, this->_internal_power(), target);
      break;
    }
    case kInnerBar: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          4, *_impl_.item_.innerbar_, _impl_.item_.innerbar_->GetCachedSize(), target, stream);
      break;
    }
    default:
      break;
  }
  // bytes properties = 5;
  if (!this->_internal_properties().empty()) {
    const std::string& _s = this->_internal_properties();
    target = stream->WriteBytesMaybeAliased(5, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Foo)
  return target;
}

::size_t Foo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Foo)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes properties = 5;
  if (!this->_internal_properties().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                    this->_internal_properties());
  }

  switch (item_case()) {
    // int32 age = 1;
    case kAge: {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this->_internal_age());
      break;
    }
    // bool is_male = 2;
    case kIsMale: {
      total_size += 2;
      break;
    }
    // double power = 3;
    case kPower: {
      total_size += 9;
      break;
    }
    // .Bar innerBar = 4;
    case kInnerBar: {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.item_.innerbar_);
      break;
    }
    case ITEM_NOT_SET: {
      break;
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void Foo::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Foo*>(&to_msg);
  auto& from = static_cast<const Foo&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:Foo)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_properties().empty()) {
    _this->_internal_set_properties(from._internal_properties());
  }
  if (const uint32_t oneof_from_case = from._impl_._oneof_case_[0]) {
    const uint32_t oneof_to_case = _this->_impl_._oneof_case_[0];
    const bool oneof_needs_init = oneof_to_case != oneof_from_case;
    if (oneof_needs_init) {
      if (oneof_to_case != 0) {
        _this->clear_item();
      }
      _this->_impl_._oneof_case_[0] = oneof_from_case;
    }

    switch (oneof_from_case) {
      case kAge: {
        _this->_impl_.item_.age_ = from._impl_.item_.age_;
        break;
      }
      case kIsMale: {
        _this->_impl_.item_.is_male_ = from._impl_.item_.is_male_;
        break;
      }
      case kPower: {
        _this->_impl_.item_.power_ = from._impl_.item_.power_;
        break;
      }
      case kInnerBar: {
        if (oneof_needs_init) {
          _this->_impl_.item_.innerbar_ =
              ::google::protobuf::Message::CopyConstruct<::Bar>(arena, *from._impl_.item_.innerbar_);
        } else {
          _this->_impl_.item_.innerbar_->MergeFrom(from._internal_innerbar());
        }
        break;
      }
      case ITEM_NOT_SET:
        break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Foo::CopyFrom(const Foo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Foo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool Foo::IsInitialized() const {
  return true;
}

void Foo::InternalSwap(Foo* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.properties_, &other->_impl_.properties_, arena);
  swap(_impl_.item_, other->_impl_.item_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::google::protobuf::Metadata Foo::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_check_2doneof_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
